'use client'

import React from 'react'
import { Page, Text, View, Document, StyleSheet, Image } from '@react-pdf/renderer'
import { JobCardData } from '../ascJobCardList'

// Define PDF styles
const styles = StyleSheet.create({
  page: { padding: 30, fontSize: 10, fontFamily: 'Helvetica' },
  header: { 
    marginBottom: 20, 
    borderBottomWidth: 1, 
    paddingBottom: 10, 
    borderColor: '#ccc',
    alignItems: 'center' // Center the logo and text
  },
  logo: {
    width: 90,      // Adjust width as needed
    height: 'auto',
    marginBottom: 10
  },
  title: { fontSize: 18, fontWeight: 'bold', marginBottom: 5, textAlign: 'center' },
  subtitle: { fontSize: 10, color: '#666', textAlign: 'center' },
  reference: { fontSize: 9, color: '#666', marginTop: 4, textAlign: 'center' },
  row: { flexDirection: 'row', marginBottom: 5 },
  col: { flexGrow: 1, width: '50%' },
  label: { fontSize: 8, color: '#666', marginBottom: 2 },
  value: { fontSize: 10, marginBottom: 8, fontWeight: 'bold' },
  section: { marginTop: 15, marginBottom: 10, padding: 10, border: '1px solid #eee', borderRadius: 4 },
  sectionTitle: { fontSize: 12, fontWeight: 'bold', marginBottom: 8, borderBottomWidth: 1, borderColor: '#eee', paddingBottom: 4 },
  pointItem: { flexDirection: 'row', marginBottom: 4 },
  bullet: { width: 10, fontSize: 10 },
  footer: { position: 'absolute', bottom: 30, left: 30, right: 30, textAlign: 'center', fontSize: 8, color: '#999', borderTopWidth: 1, paddingTop: 10 }
})

export const JobCardPDF = ({ data }: { data: JobCardData }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      {/* Header with Logo */}
      <View style={styles.header}>
        {/* Assuming the logo is in public/asc-logo.png */}
        <Image 
          src="/asc-logo.png" 
          style={styles.logo} 
        />
        <Text style={styles.title}>AUTOMOTIVE SERVICE CENTRE (ASC)</Text>
        <Text style={styles.subtitle}>Universiti Teknologi Malaysia Kuala Lumpur</Text>
        <Text style={styles.reference}>Job Card Reference: {data.job_card_id}</Text>
      </View>

      {/* Customer & Vehicle Details Grid */}
      <View style={styles.row}>
        <View style={styles.col}>
          <Text style={styles.label}>CUSTOMER NAME</Text>
          <Text style={styles.value}>{data.customer_name}</Text>

          <Text style={styles.label}>PHONE NO</Text>
          <Text style={styles.value}>{data.phone_no}</Text>

          <Text style={styles.label}>DATE IN</Text>
          <Text style={styles.value}>{new Date(data.date_in).toLocaleDateString('en-GB')}</Text>

          <Text style={styles.label}>TIME IN</Text>
          <Text style={styles.value}>{data.time_in}</Text>
        </View>
        <View style={styles.col}>
          <Text style={styles.label}>VEHICLE PLATE NO</Text>
          <Text style={styles.value}>{data.plate_no}</Text>

          <Text style={styles.label}>CAR & BRAND MODEL</Text>
          <Text style={styles.value}>{data.brand} {data.model}</Text>

          <Text style={styles.label}>CURRENT MILEAGE</Text>
          <Text style={styles.value}>{data.mileage.toLocaleString()} km</Text>

          <Text style={styles.label}>STATUS</Text>
          {/* Status color logic preserved */}
          <Text style={{ 
            ...styles.value, 
            color: data.status === 'Pending' ? '#ef4444' : data.status === 'In Progress' ? '#f59e0b' : '#10b981' 
          }}>
            {data.status.toUpperCase()}
          </Text>
        </View>
      </View>

      {/* Job Sheet Section */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>JOB SHEET / CUSTOMER POINTS</Text>
        {data.customer_points.map((point, i) => (
          <View key={i} style={styles.pointItem}>
            <Text style={styles.bullet}>•</Text>
            <Text>{point}</Text>
          </View>
        ))}
      </View>

      {/* Remarks Section */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>SERVICE ADVISOR REMARKS</Text>
        <Text style={{ lineHeight: 1.5 }}>{data.service_advisor_remark}</Text>
      </View>

      <Text style={styles.footer}>Generated by ASC System UTMKL. {new Date().toLocaleString('en-GB')}</Text>
    </Page>
  </Document>
)